# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib {{C:/Users/Admin/Desktop/New folder/Code & Software/Vivado/Heart Rate Monitor/Heart Rate Monitor.srcs/sources_1/new/Heart Rate Monitor.v}}
read_xdc {{C:/Users/Admin/Desktop/New folder/Code & Software/Vivado/Heart Rate Monitor/Heart Rate Monitor.srcs/constrs_1/new/constrain.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Admin/Desktop/New folder/Code & Software/Vivado/Heart Rate Monitor/Heart Rate Monitor.srcs/constrs_1/new/constrain.xdc}}]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Admin/Desktop/New folder/Code & Software/Vivado/Heart Rate Monitor/Heart Rate Monitor.cache/wt} [current_project]
set_property parent.project_dir {C:/Users/Admin/Desktop/New folder/Code & Software/Vivado/Heart Rate Monitor} [current_project]
catch { write_hwdef -file HeartRateMonitor.hwdef }
synth_design -top HeartRateMonitor -part xc7vx485tffg1157-1
write_checkpoint HeartRateMonitor.dcp
report_utilization -file HeartRateMonitor_utilization_synth.rpt -pb HeartRateMonitor_utilization_synth.pb
